kind: pipeline
type: docker
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      username: lechuckroh
      password:
        from_secret: docker_password
      repo: lechuckroh/gitlab-migration
      tags: latest
